branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: flask-aws-tutorial
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-east-1
  profile: eb-cli
  sc: null
