branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: flask-aws-tutorial
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: eu-west-1
  profile: eb-cli
  sc: git
